const env = (key: string, fallback?: string) => process.env[key] ?? fallback;
const num = (key: string) => (env(key) ? Number(env(key)) : undefined);

export const config = {
  rpcUrl: env("RPC_URL", "https://rpc.monad.xyz")!,
  readRpcUrl: env("READ_RPC_URL", "https://rpc.monad.xyz")!,
  wsUrl: env("WS_URL"),
  chainId: 143,
  market: env("MARKET", "0x065C9d28E428A0db40191a54d33d5b7c71a9C394")!,
  marginAccount: env("MARGIN_ACCOUNT", "0x2A68ba1833cDf93fa9Da1EEbd7F46242aD8E90c5")!,
  privateKey: env("PRIVATE_KEY"),
  dryRun: env("DRY_RUN") === "true" || !env("PRIVATE_KEY"),
  tradeSizeMon: Number(env("TRADE_SIZE_MON", "200")),
  maxPositionMon: Number(env("MAX_POSITION_MON", "1000")),
  bankrollUsd: Number(env("BANKROLL_USD", "100")),
  maxLossUsd: Number(env("MAX_LOSS_USD", "25")),
  quoteInsideTicks: Number(env("QUOTE_INSIDE_TICKS", "0")),
  marginMon: Number(env("MARGIN_MON", "600")),
  marginUsdc: Number(env("MARGIN_USDC", "20")),
  gasLimit: num("GAS_LIMIT"),
  gasLimitFallback: 450_000, // two-sided place + cancels
  maxFeeGwei: Number(env("MAX_FEE_GWEI", "400")),
  priorityFeeGwei: Number(env("PRIORITY_FEE_GWEI", "2")),
  pendingBlocks: 10,
  refreshBlocks: 200,
  horizonBlocks: Number(env("HORIZON_BLOCKS", "100")),
  model: (env("MODEL", "mock") as "mock" | "luna" | "jev"),
  jevModelId: env("JEV_MODEL_ID", "jev-latest")!,
  jevUsdPerMTok: 0.042,
  lunaApiKey: env("LUNA_API_KEY"),
  lunaBaseUrl: env("LUNA_BASE_URL"),
  lunaModel: env("LUNA_MODEL"),
  typesafeKey: env("TYPESAFE_AI_API_KEY"),
  port: Number(env("PORT", "3000")),
  historySize: 2000,
  gamma: Number(env("GAMMA", "0.1")),
  kappa: Number(env("KAPPA", "50")),
  minHalfTicks: Number(env("MIN_HALF_TICKS", "1")),
  maxHalfTicks: Number(env("MAX_HALF_TICKS", "8")),
  horizonSec: 30,
  toxicTau: 0.65,
  holdTau: 0.7,
  staleTau: 0.65,
  loopBudgetMs: 200,
  dataDir: env("DATA_DIR", "data")!,
};
